### ISSUE TITLE
Definir espacio de búsqueda, estado inicial, posible estado final, transiciones.

### ISSUE THREAD

**Issue by EmanuelTicona** [JesusRomeroRivera/cc41-tf-201910711-201910295-201911572-201910149-201914885#5]

**Comment by Nwyr-34** [comment]
[espacio_de_busqueda.md](https://github.com/JesusRomeroRivera/cc41-tf-201910711-201910295-201911572-201910149-201914885/files/7273247/espacio_de_busqueda.md)
